version: '3.4'
services:
  authz:
    container_name: app_authz
    image: mikholap/app_authz:latest
    ports:
      - "5000:5000"

  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: ./Dockerfile-nginx
    restart: on-failure
    ports:
      - "80:80"
    volumes:
      - ./nginx/logs:/var/log/nginx