replicaCount: 2
image:
  repository: mikholap/app_authz
  pullPolicy: IfNotPresent
  tag: 845101aa75a3a74118f9f5e7c4f3aa5a6b2fb178
imagePullSecrets: []
nameOverride: ''
fullnameOverride: ''
serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: authztestacc
podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext: {}
service:
  type: ClusterIP
  port: 80
  protocol: TCP
  targetport: 80
ingress:
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/use-regex: 'true'
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/service-upstream: 'true'
  hosts:
    host: api.omega.smodata.net
    http:
      paths:
        path: /authz(.*)
        pathType: ImplementationSpecific
      port: 80
  tls: []
resources: {}
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
volumes: []
volumeMounts:
  name: nginx-config
  mountPath: /etc/nginx
nodeSelector: {}
tolerations: []
affinity: {}
deployment:
  strategy:
    type: RollingUpdate
    maxSurge: 2
  template:
    specNginx:
      name: nginx
      image: nginx:1.25.2
      ports:
        containerPort: 80
        name: http
        protocol: TCP
labels:
  app: authz
  bank: omegabank
  env: prd
