apiVersion: v1

name: authz
labels:
  app: authz
  bank: omega
  env: prd
ports:
  containerPort: 80
  name: http
  protocol: TCP

# deployment values
annotations:
  useregex: "true"
  rewritetarget: /$1
strategy:
  type: RollingUpdate
rollingUpdate:
      maxSurge: 2
containers:
 name: nginx
 image: nginx:1.25.2
volumeMounts:
  name: nginx-config
  mountPath: /etc/nginx
image:
  name: mikholap/app_authz
  tag: latest
replicas: 2  
# ingress value
host:
  name: omega
  domain: smodata.net
port:
  number: 80
ingressClassName: nginx

#service
servicePorts:
  protocol: TCP
  port: 80
  targetPort: 80