name: authz
labels:
  app: authz
  bank: omega
  env: prd
ports:
  containerPort: 80
  name: http
  protocol: TCP

# deployment values
annotations:
  useregex: '"true"'
  rewritetarget: /$1
strategy:
  type: RollingUpdate
rollingUpdate:
      maxSurge: 2
containers:
 name: nginx
 image: nginx:1.25.2
volumeMounts:
  name: nginx-config
  mountPath: /etc/nginx
image:
  name: mikholap/app_authz
  tag: 83834a6ac839fa51f9d5b6f104003f7d587ce6b2
replicas: 2  

# ingress values
host: api.omega.smodata.net
port:
  number: 80
ingressClassName: nginx

#service values
servicePorts:
  protocol: TCP
  port: 80
  targetPort: 80

#serviceaccount
serviceAccount:
  name: authz-service-account
  automount: true
  srvctoken: true
  annotations: {}
  