apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authz
  # You'll usually want to add your resources to the argocd namespace.
  namespace: omegabank
  # Add this finalizer ONLY if you want these to cascade delete.
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  # The project the application belongs to.
  project: default

  # Source of the application manifests
  source:
    repoURL: https://github.com/avmikholap/dos14-Miholap_Aleksey_git-flow.git
    targetRevision: feature-helm-chart
    path: charts/authz

    helm:
      releaseName: omegabank-authz
      valueFiles:
      - /charts/authz/values/aws-prd.yaml
  destination:
    server: "https://1D740396F34543A99F12858947ABAD69.gr7.eu-west-1.eks.amazonaws.com"
    namespace: omegabank



    # repoURL: https://github.com/avmikholap/dos14-Miholap_Aleksey_git-flow.git  # Can point to either a Helm chart repo or a git repo.
    # targetRevision: feature-helm-chart  # For Helm, this refers to the chart version.
    # path: charts/authz # This has no meaning for Helm charts pulled directly from a Helm repo instead of git.

  # # Destination cluster and namespace to deploy the application
  # destination:
  #   server: https://1D740396F34543A99F12858947ABAD69.gr7.eu-west-1.eks.amazonaws.com
  #   namespace: omegabank

  # Sync policy
  syncPolicy:
    automated: # automated sync by default retries failed attempts 5 times with following delays between attempts ( 5s, 10s, 20s, 40s, 80s ); retry controlled using `retry` field.
      prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
    syncOptions:     # Sync options which modifies sync behavior
    - CreateNamespace=true # Namespace Auto-Creation ensures that namespace specified as the application destination exists in the destination cluster.