apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authz-omegabank
  # annotations:
  #   argocd-image-updater.argoproj.io/image-list: mikholap/app_authz:0.0.5
    # argocd-image-updater.argoproj.io/write-back-method: git
  namespace: omegabank
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: omegabank
  source:
    repoURL: 'https://github.com/avmikholap/dos14-Miholap_Aleksey_git-flow.git'
    targetRevision: feature-CD
    path: charts/authz
    helm:
      valueFiles:
        - values.yaml
      releaseName: omegabankauthz
  destination:
    server: 'https://1D740396F34543A99F12858947ABAD69.gr7.eu-west-1.eks.amazonaws.com'
    namespace: omegabank
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Validate=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
