apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-svc
  namespace: {{ .Release.Namespace }}
spec:
  type: ExternalName
  externalName: omegabank-rds-tf.cearikylb8tb.eu-west-1.rds.amazonaws.com