apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.name }}-serviceaccount
  automountServiceAccountToken: {{ .Values.srvctoken }}
  labels:
    bank: {{ .Values.labels.bank }}
    env: {{ .Values.labels.env }}
 