apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-svc
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - protocol: {{ .Values.servicePorts.protocol }}
      port: {{ .Values.servicePorts.port }}
      targetPort: {{ .Values.servicePorts.targetPort  }}
  selector:
    app: {{ .Values.labels.app }}
    bank: {{ .Values.labels.bank }}
    env: {{ .Values.labels.env }}